### ISSUE TITLE
Does not load image in the SDAnimatedImageView (intermittent issue)

### ISSUE THREAD

**Issue by anmolagar** [SDWebImage/SDWebImagePhotosPlugin#1]
> Since Photos Library image is already stored on the device disk. And query speed is fast enough for small resolution image. You can use SDWebImageContextStoreCacheType with SDImageCacheTypeNone to disable cache storage. And use SDWebImageFromLoaderOnly to disable cache query.

This does not load image sometimes in the SDAnimatedImageView.

**Comment by dreampiggy** [comment]
@anmolagar Hi. Thanks for the report.

The Photos Plugin is just a loader, to load the normal `UIImage` stored in the iOS device photos library. Therefore the image in the `completionBlock` is always actually the `UIImage` class but not something like `SDAnimatedImage` for animation.

Could you please help me provide some extra information ? For example, how do you register the Photos Loader during image loading ? Did you assign it into the shared manager to using the context option to just use a single manager ?

```objectivec
SDWebImageManager *manager = [[SDWebImageManager alloc] initWithCache:SDImageCache.sharedCache loader:SDWebImagePhotosLoader.sharedLoader];
[imageView sd_setImageWithURL:photosURL placeholderImage:nil context:@{SDWebImageCustomManager: manager}];
```

And, could you please add a completionBlock for `sd_setImageWithURL:` method, in the completionBlock, check the `image` arg, is that valid ? 

```objectivec
[cell.customImageView sd_setImageWithURL:self.objects[indexPath.row]
                        placeholderImage:placeholderImage
                                 options:SDWebImageFromLoaderOnly
                                 context:@{SDWebImageContextStoreCacheType : @(SDImageCacheTypeNone)}
                                progress:nil
                               completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
                                     // Debug or log to check whether the image is valid ?
                                     NSParameterAssert(image);
                                 }];
```

**Comment by dreampiggy** [comment]
@anmolagar Our [demo](https://github.com/SDWebImage/SDWebImagePhotosPlugin#demo) also use `SDAnimatedImageView`, could you try to clone and modify the code to simulate your use case, and test whether this issue can be reproduced ?

**Comment by anmolagar** [comment]
Hi @dreampiggy ,
My project has both the use case of getting images from Photo library as well as getting from the web. So I am wondering, could this be a conflicting scenario?

**Comment by dreampiggy** [comment]
@anmolagar See the readme again. I update the step-by-step tutorial about how to register loader for `SDWebImageManager` based on two different use cases.

https://github.com/SDWebImage/SDWebImagePhotosPlugin#usage

Actually it's not so magic, you should use the [loader manager (multiple loaders)](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#loaders-manager) to register both `SDWebImageDownloader` && `SDWebImagePhotosLoader`, then all things done :)
