### ISSUE TITLE
Request completion block

### ISSUE THREAD

**Issue by 4hakke** [SDWebImage/SDWebImagePhotosPlugin#11]
Hi! I wonder if it is possible to get **completion block** after photo loading was completed for following method: 
`imageView.sd_setImage(with: photoURL, placeholderImage: nil, context [.photosImageRequestOptions: requestOptions])`
Thanks in advance!

**Comment by dreampiggy** [comment]
.So why not just using `imageView.sd_setImage(with: photoURL, placeholderImage: nil, context [.photosImageRequestOptions: requestOptions] progress: nil, completed:myCompletion)` ? The public API for UIImageView is the exact same as SDWebImage for web images.

**Comment by 4hakke** [comment]
Oh, haven't noticed it. I'm terrible sorry. Closing it.
