### ISSUE TITLE
Extremely high memory usage and slow scrolling

### ISSUE THREAD

**Issue by aheze** [SDWebImage/SDWebImagePhotosPlugin#17]
### New Issue Checklist

* [x] I have read the tutorial [usage](https://github.com/SDWebImage/SDWebImagePhotosPlugin#usage)
* [X] I have searched for a similar issue in the [project](https://github.com/SDWebImage/SDWebImagePhotosPlugin/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.2
 Framework Version       | SDWebImage (5.8.3), SDWebImagePhotosPlugin (1.1.0)
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12
 Repro rate              | 100%
 Repro with our demo prj | No
 Demo project link       | https://github.com/aheze/PhotoLoading

### Issue Description and Steps

The collection view scrolls choppily, and the memory goes over 1 gb, depending on how many photos you have. It sometimes also crashes due to `Terminated due to memory error`.

![Screen Shot 2020-12-30 at 8 07 04 PM](https://user-images.githubusercontent.com/49819455/103394162-a9ae5580-4adb-11eb-9f7a-171770295de7.png)

I followed the example project (it's in Objective-C so I probably misread some things), first doing this inside `viewDidLoad()`:

```Swift
//Supports HTTP URL as well as Photos URL globally
SDImageLoadersManager.shared.loaders = [SDWebImageDownloader.shared, SDImagePhotosLoader.shared]

// Replace default manager's loader implementation
SDWebImageManager.defaultImageLoader = SDImageLoadersManager.shared

let options = PHImageRequestOptions()
options.sd_targetSize = CGSize(width: 500, height: 500) /// make sure don't load too big
SDImagePhotosLoader.shared.imageRequestOptions = options
```

Instead of an array of `NSURL` I used an array of `PHAsset`:

```Swift
var allPhotos: PHFetchResult<PHAsset>? = nil
...
PHPhotoLibrary.requestAuthorization { (status) in /// request access inside ViewDidLoad
    if status == .authorized {
        let fetchOptions = PHFetchOptions()
        self.allPhotos = PHAsset.fetchAssets(with: .image, options: fetchOptions)
        DispatchQueue.main.async {
            self.collectionView.reloadData() /// reload collectionview once done
        }
    }
}
```

And this is my `cellForRowAt`. I make the `NSURL` here.

```Swift
func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
  let cell = collectionView.dequeueReusableCell(withReuseIdentifier: reuseID, for: indexPath) as! CollectionViewCell
  
  let asset = allPhotos![indexPath.item]
  let photosURL = NSURL.sd_URL(with: asset)
  cell.imageView.sd_setImage(with: photosURL as URL?, placeholderImage: nil, options: SDWebImageOptions.fromLoaderOnly)
  return cell
}
```
My full code is all in [`ViewController.swift`](https://github.com/aheze/PhotoLoading/blob/main/PhotoLoading/ViewController.swift) (63 lines). What am I doing wrong? Thanks for any help!

**Comment by aheze** [comment]
I replaced
```Swift
cell.imageView.sd_setImage(with: photosURL as URL?, placeholderImage: nil, options: SDWebImageOptions.fromLoaderOnly)
```
with
```Swift
cell.imageView.sd_setImage(with: photosURL as URL?, placeholderImage: nil, options: SDWebImageOptions.fromLoaderOnly, context: [SDWebImageContextOption.storeCacheType: SDImageCacheType.none.rawValue])
```
The scrolling is much better, but it sometimes freezes. When it freezes, the memory still spikes to around 900 mb. However, once I scroll a little, it drops back down to ~80mb.

<img width="1231" alt="Screen Shot 2020-12-30 at 9 58 10 PM" src="https://user-images.githubusercontent.com/49819455/103396818-234d4000-4aea-11eb-9fe1-79212c3b51e9.png">

**Comment by dreampiggy** [comment]
You should limit the image size, or it will query original image size (Update to your iPhone's Camera like 4K/5K size):


https://github.com/SDWebImage/SDWebImagePhotosPlugin#control-query-image-size

**Comment by aheze** [comment]
@dreampiggy thanks, works perfectly!

<img width="1330" alt="Screen Shot 2020-12-30 at 11 18 43 PM" src="https://user-images.githubusercontent.com/49819455/103399324-65c84a00-4af5-11eb-9fa9-159eac282bd3.png">

Here's the final `cellForItemAt` in case anyone else needs it:

```Swift
func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
  let cell = collectionView.dequeueReusableCell(withReuseIdentifier: reuseID, for: indexPath) as! CollectionViewCell
  
  let asset = allPhotos![indexPath.item]
  let photosURL = NSURL.sd_URL(with: asset)
  cell.imageView.sd_setImage(with: photosURL as URL?, placeholderImage: nil, options: SDWebImageOptions.fromLoaderOnly, context: [SDWebImageContextOption.storeCacheType: SDImageCacheType.none.rawValue, .imageThumbnailPixelSize : cell.bounds.size])
  return cell
}
```
