### ISSUE TITLE
Support for URL instead of NSURL

### ISSUE THREAD

**Issue by aheze** [SDWebImage/SDWebImagePhotosPlugin#18]
### New Feature Request Checklist

* [X] I have checked the current documentations or APIs and did not find a solution
* [X] I have searched for a similar issue in the [project](https://github.com/SDWebImage/SDWebImagePhotosPlugin/issues) and found none

### Feature Request Description

Currently, you make a `NSURL` from `PHAsset` like this:
```Swift
// Create with `PHAsset`
let asset: PHAsset
let photosURL = NSURL.sd_URL(with: asset)

// Load image (assume using custom manager)
imageView.sd_setImage(with: photosURL, placeholderImage: nil, context: [.customManager: manager])
```
However, `sd_setImage(with:` takes a `URL`, not `NSURL`.

<kbd>![Screen Shot 2020-12-30 at 8 20 47 PM](https://user-images.githubusercontent.com/49819455/103394298-88019e00-4adc-11eb-9a9f-0d48dab265cf.png)</kbd>

I would like to be able to get a `URL` from `PHAsset`, something like this:

```Swift
// Create with `PHAsset`
let asset: PHAsset
let photosURL = URL.sd_URL(with: asset) /// URL not NSURL

// Load image (assume using custom manager)
imageView.sd_setImage(with: photosURL, placeholderImage: nil, context: [.customManager: manager])
```
This would avoid the error, and I think URLs are safer than NSURLs.

**Comment by dreampiggy** [comment]
This is limit in current Pure Objective-C implementation...

That `NSURL` category return type can not been autoamtically converted into `URL` sturct and may loss information.

**Comment by dreampiggy** [comment]
Can the `Fix-it` with `as URL?` solve the issue ?

**Comment by aheze** [comment]
@dreampiggy yes, `as URL?` works.

```Swift
let asset: PHAsset
let photosURL = NSURL.sd_URL(with: asset)
cell.imageView.sd_setImage(with: photosURL as URL?, placeholderImage: nil) /// this works
```

**Comment by dreampiggy** [comment]
I'll update readme now.

For better Swift support, let me find some other way, or provide something like https://github.com/SDWebImage/SDWebImage/issues/2980

Provide this repo as an Objective-C/Swift Mixed project.

**Comment by dreampiggy** [comment]
@aheze Introduce the convenience API for Swift user. See #21

```swift
let asset: PHAsset
let url = asset.sd_URLRepresentation
```
