### ISSUE TITLE
unsupported URL

### ISSUE THREAD

**Issue by BharatAgarSoftTech** [SDWebImage/SDWebImagePhotosPlugin#2]
2018-09-04 18:31:24.318357+0530 [1690:202387] Task <65A83068-4467-4DBA-B035-720EBB27A59A>.<7> finished with error - code: -1002
2018-09-04 18:31:24.337494+0530 [1690:202405] Task <65A83068-4467-4DBA-B035-720EBB27A59A>.<7> load failed with error Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=photos://asset/82CCD013-F7E9-461F-8F36-5E3A4FCAD6BB/L0/001, NSErrorFailingURLKey=photos://asset/82CCD013-F7E9-461F-8F36-5E3A4FCAD6BB/L0/001, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <65A83068-4467-4DBA-B035-720EBB27A59A>.<7>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <65A83068-4467-4DBA-B035-720EBB27A59A>.<7>, NSUnderlyingError=0x281b02ac0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}} [-1002]

**Comment by BharatAgarSoftTech** [comment]
I just add below three files inside my project and pushing to MasterViewController
MasterViewController.xib
MasterViewController.h
MasterViewController.m

**info.plist information** 
Allow Arbitrary Loads YES
Privacy - Photo Library Usage Description is added

**padlock info**
  - SDWebImage/Core (5.0.0-beta3)
  - SDWebImagePhotosPlugin (0.1.0):
    - SDWebImage/Core (~> 5.0.0-beta)

**Comment by dreampiggy** [comment]
@BharatAgarSoftTech Hi. From the `NSURLErrorDomain`, it seems that the `SDWebImagePhotosLoader` was not registered to your `SDWebImageManager` during image loading. By default it use `SDWebImageDownloader` and supports `HTTP/HTTPS/FTP` image URLs only.

I update the readme and introduce detailed step by step tutorial for beginners. You can try to look at [SDWebImagePhotosPlugin-Usage](https://github.com/SDWebImage/SDWebImagePhotosPlugin#usage) again.

If still have some issue, you can also run our demo to check is there anything wrong with your code or the configuration. Waiting for response.

**Comment by BharatAgarSoftTech** [comment]
@dreampiggy Thanks for quick reply.

Right now i am changing default image loader to PhotosLoader using below code
SDWebImageManager.defaultImageLoader = [SDWebImagePhotosLoader sharedLoader];

And loading image like this.
[cell.customImageView sd_setImageWithURL:self.objects[indexPath.row]
                            placeholderImage:placeholderImage
                                     options:SDWebImageFromLoaderOnly
                                     context:@{SDWebImageContextStoreCacheType : @(SDImageCacheTypeNone)}];

When I tried to use SDImageCache and SDWebImageCustomManager its showing following errors.
Property 'sharedCache' not found on object of type 'SDImageCache'
Use of undeclared identifier 'SDWebImageCustomManager'

**Comment by dreampiggy** [comment]
@BharatAgarSoftTech My typo. Use `[SDImageCache  sharedImageCache]` && `SDWebImageContextCustomManager` in Objective-C. I updated the readme as well.

**Comment by BharatAgarSoftTech** [comment]
@dreampiggy Thanks for the support its working now :)

Here is the working code

// Setup Photos Loader    
SDWebImageManager.defaultImageLoader = [SDWebImagePhotosLoader sharedLoader];

// Setup Manager
SDWebImageManager *manager = [[SDWebImageManager alloc] initWithCache:SDImageCache.sharedImageCache loader:SDWebImagePhotosLoader.sharedLoader];

// Loading image
[cell.customImageView sd_setImageWithURL:self.assetArray[indexPath.row] placeholderImage:nil options:SDWebImageFromLoaderOnly context:@{SDWebImageContextCustomManager: manager}];

**Comment by dreampiggy** [comment]
@BharatAgarSoftTech That first line of code, will effect shared `SDWebImageManager` to use Photos loader only. So when you load HTTP URLs using `sd_setImageWithURL:` without using that `SDWebImageContextCustomManager` context option, you will get error because you disable `SDWebImageDownloader`.

The correct way, is to assign the `SDImageLoadersManager` into `defaultImageLoader`. It's a multiple loaders manager. You can supply one or more actual loaders into its' `loaders` array.

```objective-c
// Supports HTTP URL as well as Photos URL globally
SDImageLoadersManager.sharedManager.loaders = @[SDWebImageDownloader.sharedDownloader, SDWebImagePhotosLoader.sharedLoader];
// Replace default manager's loader implementation
SDWebImageManager.defaultImageLoader = SDImageLoadersManager.sharedManager;
```
