### ISSUE TITLE
Is it possible to have SDWebImagePhotosPlugin work with SDWebImage v.5.10.X using SPM?

### ISSUE THREAD

**Issue by petershab** [SDWebImage/SDWebImagePhotosPlugin#20]
### New Feature Request Checklist

* [x] I have checked the current documentations or APIs and does not find a solution
* [x] I have searched for a similar issue in the [project](https://github.com/SDWebImage/SDWebImagePhotosPlugin/issues) and found none
 I seem to be able to only make it work with 5.9.X. You run into the dreaded 
"The package product 'iOSAnyPackage' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0" error outlined here https://forums.swift.org/t/xcode12-minimum-deployment-target-and-spm/40467 when you update your package. 
There seem to be ways to do this using CocoaPods, but I am having trouble finding anything useful when working with SPM.

### Feature Request Description

Please fill in the detailed description about feature request, including the feature use case (what you need) and the solution you want (like usage, demo code, ...)

**Comment by dreampiggy** [comment]
I'll provide a update quickly to bump the min deployment target version of `SDWebImagePhotosPlugin` itself.
