### ISSUE TITLE
I am seeing the same issue using SDWebImage version 5.3.2, cocoapods, Xcode 12. Crashes are appearing on iOS 14+, does not appear to be happening below iOS 14.

### ISSUE THREAD

**Issue by papac25** [SDWebImage/SDWebImagePhotosPlugin#23]
I am seeing the same issue using SDWebImage version 5.3.2, cocoapods, Xcode 12. Crashes are appearing on iOS 14+, does not appear to be happening below iOS 14.

_Originally posted by @poiuyqwert in https://github.com/SDWebImage/SDWebImage/issues/3124#issuecomment-726898987_

**Comment by dreampiggy** [comment]
Try the latest SDWebImage version (update to 5.10.4)
