### ISSUE TITLE
Only support image

### ISSUE THREAD

**Issue by robinchanme** [SDWebImage/SDWebImagePhotosPlugin#9]
Only support PHAssetMediaTypeImage
pls support PHAssetMediaTypeVideo too

**Comment by dreampiggy** [comment]
@jasparchan One question, what type of image for `PHAssetMediaTypeVideo` do you want ? The placeholder image of first frame ? Or the **Best Match** frame ? Or even with customization (for example, you give me the timestamp or frame index)

**Comment by dreampiggy** [comment]
I'll have a try to see **If Apple's PHImageManager supports to grab a image from `PHAssetMediaTypeVideo` asset**. If it does, I can simply add a new option for you, to disable the image type check when query PHAssets.

**Comment by dreampiggy** [comment]
@jasparchan See #10. The Video Asset can used for PHImageManager request, so this limit should not be hardcoded

**Comment by dreampiggy** [comment]
Supported Video Assets in v0.4.0. Close this issue.
